apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privilege-escalation
  annotations:
    policies.kyverno.io/title: Disallow Privilege Escalation
    policies.kyverno.io/category: Pod Security
    policies.kyverno.io/description: >-
      Containers must not be allowed to escalate privileges via allowPrivilegeEscalation.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: deny-privilege-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - aetherion
      validate:
        message: "Privilege escalation is not allowed. Set allowPrivilegeEscalation: false."
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
